_extends: jellyfin-meta-plugins

template: |
  <!-- Optional: add a release summary here -->
  [Plugin build can be downloaded from GitHub Releases](https://github.com/redeuxx/jellyfin-plugin-retrak/releases).

  ## :sparkles: What's New

  $CHANGES
